AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  FunctionName:
    Type: String
  SNSTopic:
    Type: String
  LINE_NOTIFY_TOKEN:
    Type: String
Resources:
  Function:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: 'python3.8'
      Handler: 'lambda_function.lambda_handler'
      Tracing: 'PassThrough' # or Active
      Environment:
        Variables:
          LINE_NOTIFY_TOKEN: !Ref LINE_NOTIFY_TOKEN
      # main と指定すると fork/exec /var/task/main: permission denied: PathError
      CodeUri: '.'
      FunctionName: !Ref FunctionName
      Description: 'post sns messages to slack incoming webhooks'
      MemorySize: 128
      Timeout: 5
      # Role: 
      # if Role property is set, Policies property has no meaning
      Policies:
        - AWSLambdaBasicExecutionRole
      Events: 
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref Topic
      Tags:
        Key: 'Value'
  Topic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Ref SNSTopic